name: camera_pkg
description: Camera package combined with image quality compressor and cropper.
version: 0.0.1
homepage:

environment:
  sdk: '>=3.0.2 <4.0.0'
  flutter: ">=3.10.3"

dependencies:
  flutter:
    sdk: flutter

  camera:
  video_player:
  image_cropper:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

